project:
  type: website
  output-dir: docs

website:
  title: "小林光木 | 成蹊大学 理工学部 データサイエンス研究室 助教"
  search: false
  navbar:
    right:
      - text: "研究活動"
        href: research.qmd
      - text: "授業・教材"
        href: teaching.qmd
      - text: "連絡先・アクセス"
        href: contact.qmd
      - text: "外部リンク"
        href: links.qmd
  sidebar:
    - id: teaching
      contents:
        - section: "授業・教材"
          href: teaching.qmd
          contents:
            - section: "微分方程式"
              href: teaching/differential-equations.qmd
              contents:
                - text: "高階定数係数斉次線形微分方程式"
                  href: teaching/differential-equations/self-study/higher-order-constant-coefficient-homogeneous.qmd
                - text: "多項式を非斉次項にもつ場合"
                  href: teaching/differential-equations/self-study/higher-order-polynomial-nonhomogeneous.qmd
            - section: "プログラミング基礎（Python）"
              href: teaching/programming-basics-python.qmd
              contents:
                - section: "授業案内"
                  contents:
                    - text: "シラバス"
                      href: "https://portal.seikei.ac.jp/campusweb/slbssbdr.do?value%28risyunen%29=2026&value%28semekikn%29=1&value%28kougicd%29=123020020&value%28crclumcd%29=58888-0110"
                    - text: "履修上の注意"
                      href: teaching/programming-basics-python/course-guidance.qmd
                - section: "オンライン教材"
                  contents:
                    - section: "第1部　Pythonの基礎"
                      contents:
                        - text: "第2章　変数と代入"
                          href: teaching/programming-basics-python/fundamentals/variables-assignment.qmd
                    - section: "スライド資料"
                      contents:
                        - text: "第2回　プログラムの基本"
                          href: teaching/programming-basics-python/slides/variables-assignment.qmd
            - text: "C++プログラミングⅠ"
              href: teaching/cpp-programming-1.qmd
            - section: "WSL + Ubuntu 環境構築"
              href: teaching/wsl-ubuntu-setup/index.qmd
              contents:
                - text: "WSLをインストール"
                  href: teaching/wsl-ubuntu-setup/videos/wsl-install/index.qmd
                - text: "Ubuntuをインストールして初回設定"
                  href: teaching/wsl-ubuntu-setup/videos/ubuntu-install/index.qmd
                - text: "C++ の開発ツールを導入する"
                  href: teaching/wsl-ubuntu-setup/videos/gpp-install/index.qmd
                - text: "授業用フォルダを作成して登録する"
                  href: teaching/wsl-ubuntu-setup/videos/work-folder-setup/index.qmd
                - text: "ファイル名拡張子を表示する"
                  href: teaching/wsl-ubuntu-setup/videos/show-file-extensions/index.qmd
                - text: "WSL のバージョン確認と更新"
                  href: teaching/wsl-ubuntu-setup/videos/wsl-version-update/index.qmd

format:
  html:
    lang: ja
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true
