project:
  type: website
  output-dir: docs

website:
  title: "小林光木 | 成蹊大学 理工学部 データサイエンス研究室 助教"
  search: false
  navbar:
    right:
      - text: "研究活動"
        href: research.qmd
      - text: "授業・教材"
        href: teaching.qmd
      - text: "連絡先・アクセス"
        href: contact.qmd
      - text: "外部リンク"
        href: links.qmd
  sidebar:
    - id: teaching
      contents:
        - section: "授業・教材"
          href: teaching.qmd
          contents:
            - section: "微分方程式"
              href: teaching/differential-equations.qmd
              contents:
                - auto: teaching/differential-equations/self-study/*.qmd

format:
  html:
    lang: ja
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true
